In [1]:

import pandas as pd

from sklearn.datasets import load_diabetes, load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.metrics import (
    r2_score,
    mean_squared_error,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

# PART 1: REGRESSION

diabetes = load_diabetes()
X = diabetes.data
y = diabetes.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

regression_models = {
    "Linear Regression": LinearRegression(),
    "Random Forest": RandomForestRegressor(
        n_estimators=100, random_state=42
    )
}

regression_results = []

for name, model in regression_models.items():
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)

    regression_results.append({
        "Model": name,
        "R2 Score": round(r2_score(y_test, predictions), 3),
        "RMSE": round(mean_squared_error(
            y_test, predictions
        ) ** 0.5, 3)
    })

print("REGRESSION RESULTS")
display(pd.DataFrame(regression_results))


# PART 2: CLASSIFICATION

cancer = load_breast_cancer()
X = cancer.data
y = cancer.target

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2,
    random_state=42, stratify=y
)

classification_models = {
    "Logistic Regression": make_pipeline(
        StandardScaler(),
        LogisticRegression(max_iter=2000)
    ),
    "Decision Tree": DecisionTreeClassifier(
        random_state=42
    )
}

classification_results = []

for name, model in classification_models.items():
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)

    classification_results.append({
        "Model": name,
        "Accuracy": round(
            accuracy_score(y_test, predictions), 3
        ),
        "Precision": round(
            precision_score(y_test, predictions), 3
        ),
        "Recall": round(
            recall_score(y_test, predictions), 3
        ),
        "F1 Score": round(
            f1_score(y_test, predictions), 3
        )
    })

print("CLASSIFICATION RESULTS")
display(pd.DataFrame(classification_results))

print("Week 2 task completed successfully!")

REGRESSION RESULTS

               Model  R2 Score    RMSE
0  Linear Regression     0.453  53.853
1      Random Forest     0.443  54.332

CLASSIFICATION RESULTS

                 Model  Accuracy  Precision  Recall  F1 Score
0  Logistic Regression     0.982      0.986   0.986     0.986
1        Decision Tree     0.912      0.956   0.903     0.929

Week 2 task completed successfully!